### ISSUE TITLE
Support writing in caps

### ISSUE THREAD

**Issue by ges134** [Adam-Jimenez/kebac#1]
![image](https://user-images.githubusercontent.com/10748580/56672493-8aafbd00-6684-11e9-87d8-0f4e50d5389f.png)

Sudo bots queries over the API and when writing in caps, the translation doesn't seem to work. Might be cool if we want to get aggressive or, un kébécois en tabarnak. 😄

**Comment by Adam-Jimenez** [comment]
fixed
